### ISSUE TITLE
How to change the background color of checked toggles?

### ISSUE THREAD

**Issue by jvolker** [beyonk-group/gdpr-cookie-consent-banner#57]
First of all, thanks for writing and sharing this component.
 
I'd like to change the background-color of only the checked toggles.

This works to turn all of them green, even the unchecked ones:

```css
<style>

:global(.cookieConsentOperations__Item label::before) {
	background-color: green !important;
}

</style>
```

<img width="455" alt="image" src="https://github.com/beyonk-group/gdpr-cookie-consent-banner/assets/546852/1a9a518c-1912-45be-ac0a-a125862c07e8">

I've tried this to target only the checked ones using the following code:

```css
<style>

:global(.cookieConsentOperations__Item label::part(operations--list-item-label--checked)::before) {
	background-color: green !important;
}

</style>
```

Unfortunately, with this, none of them turn green. How to do this correctly?

Thanks a lot in advance.
